#!/bin/bash
# Script to set up the CLA environment on the VM

# Connect to the VM and run these commands
echo "Run the following commands on your VM after connecting via SSH:"
echo "=================================="
echo "# Fix the missing config and permissions issues"
echo ""
echo "# 1. Stop the service to prevent restart loops"
echo "sudo systemctl stop cla.service"
echo ""
echo "# 2. Create the config directory and file"
echo "cd /home/app/ai-driven-soc"
echo "mkdir -p config"
echo ""
echo "# 3. Create the config file with correct BigQuery settings"
echo "cat > config/cla_config.json << 'EOF'"
echo "{"
echo "  \"project_id\": \"chronicle-dev-2be9\","
echo "  \"bigquery_dataset\": \"soc_data\","
echo "  \"bigquery_alerts_table\": \"alerts\","
echo "  \"bigquery_feedback_table\": \"feedback\","
echo "  \"bigquery_metrics_table\": \"metrics\","
echo "  \"bigquery_models_table\": \"models\","
echo "  \"bigquery_evaluations_table\": \"evaluations\","
echo "  \"bigquery_incidents_table\": \"incidents\","
echo "  \"bigquery_patterns_table\": \"patterns\","
echo "  \"bigquery_improvements_table\": \"improvements\","
echo "  \"bigquery_agent_state_table\": \"agent_state\","
echo "  \"feedback_topic\": \"soc-feedback\","
echo "  \"feedback_subscription\": \"cla-feedback-sub\","
echo "  \"metrics_topic\": \"soc-metrics\","
echo "  \"metrics_subscription\": \"cla-metrics-sub\","
echo "  \"langgraph_feedback_topic\": \"langgraph-feedback\","
echo "  \"feedback_threshold\": 10,"
echo "  \"retraining_interval_days\": 7,"
echo "  \"model_improvement_threshold\": 0.05,"
echo "  \"metrics_collection_days\": 30,"
echo "  \"pattern_analysis_days\": 30"
echo "}"
echo "EOF"
echo ""
echo "# 4. Modify the continuous-learning-agent.py file to fix any remaining Firestore references"
echo "# IMPORTANT: We need to edit the file to replace Firestore with BigQuery"
echo "cd /home/app/ai-driven-soc"
echo "cp continuous-learning-agent.py continuous-learning-agent.py.bak"
echo ""
echo "# 5. Update the systemd service file"
echo "sudo bash -c 'cat > /etc/systemd/system/cla.service << EOF"
echo "[Unit]"
echo "Description=Continuous Learning Agent for AI-Driven SOC"
echo "After=network.target"
echo ""
echo "[Service]"
echo "Type=simple"
echo "User=raditio.ghifiardigmail.com"
echo "Group=raditio.ghifiardigmail.com"
echo "WorkingDirectory=/home/app/ai-driven-soc"
echo "ExecStart=/home/app/ai-driven-soc/venv/bin/python /home/app/ai-driven-soc/continuous-learning-agent.py --config /home/app/ai-driven-soc/config/cla_config.json"
echo "Restart=always"
echo "RestartSec=10"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF'"
echo ""
echo "# 6. Reload and restart the service"
echo "sudo systemctl daemon-reload"
echo ""
echo "# 7. Open the agent file and edit it to replace the Firestore reference with BigQuery"
echo "# Here's the line you need to fix in process_feedback():"
echo "# Change:"
echo "#   self.db.collection(\"feedback\").document(alert_id).set(feedback_doc)"
echo "# To:"
echo "#   table_id = f\"{self.project_id}.{self.bigquery_dataset}.{self.bigquery_feedback_table}\""
echo "#   self.bq_client.insert_rows_json(table_id, [feedback_doc])"
echo ""
echo "# 8. After editing, start the service and check logs"
echo "sudo systemctl start cla.service"
echo "sudo journalctl -u cla.service -f"
echo "=================================="
