#!/bin/bash
# SOC Services Startup Script
# Generated by SOC Service Manager


# Start Services
streamlit run streamlit_soc_dashboard.py --server.port 8501 --server.address 0.0.0.0 &
streamlit run streamlit_soc_dashboard_minimal.py --server.port 8502 --server.address 0.0.0.0 &
streamlit run realtime_soc_dashboard.py --server.port 8504 --server.address 0.0.0.0 &
streamlit run local_bigquery_app.py --server.port 8505 --server.address 0.0.0.0 &

# Check Processes
ps aux | grep streamlit
netstat -tulpn | grep :85
top -p $(pgrep streamlit | tr '\n' ',' | sed 's/,$//')

# Stop Services
pkill -f streamlit
lsof -ti:8501 | xargs kill -9

# Restart Services
pkill -f streamlit
sleep 5
streamlit run streamlit_soc_dashboard.py --server.port 8501 --server.address 0.0.0.0 &
streamlit run streamlit_soc_dashboard_minimal.py --server.port 8502 --server.address 0.0.0.0 &

# Monitor Services
tail -f ~/.streamlit/logs/streamlit.log
htop
df -h
free -h

# Backup Services
tar -czf soc_dashboards_backup_$(date +%Y%m%d_%H%M%S).tar.gz *.py *.md *.txt
cp -r config/ config_backup_$(date +%Y%m%d_%H%M%S)/
cp *.json keys_backup_$(date +%Y%m%d_%H%M%S)/
